#!/bin/bash

echo 'Problem name: '
read NAME
echo '/*
ID: frequen1
PROG: '"$NAME"'
LANG: C++
*/
#include <iostream>
#include <fstream>
#include <string>
#include <algorithm>
#include <cstdio>
#include <stack>
#include <queue>
#include <set>
#include <map>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <iomanip>
#include <utility>
using namespace std;
const long oo = (1LL<<31)-1;
ifstream fin ("'"$NAME.in"'");
ofstream fout ("'"$NAME.out"'");

int main(int argc, char *argv[])
{

  return 0;
}
' > "$NAME.cpp"
touch "$NAME.in"
emacs "$NAME.cpp" "$NAME.in"
